name: CD

on:
  release:
    types: [published]
      
jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Publish package
      run: ./gradlew publish
      env:
        ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRHPASSWORD }}
        ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRHUSERNAME }}
        ORG_GRADLE_PROJECT_pgpSigningKey: ${{ secrets.PGPSIGNINGKEY }}
        ORG_GRADLE_PROJECT_pgpSigningPassword: ${{ secrets.PGPSIGNINGPASSWORD }}
        
    - name: Build LSP
      run: mvn verify

    - name: Publish repository
      run: mvn deploy -Prelease-composite -Dgithub-update-repo=https://x-access-token:${GITHUB_TOKEN}@github.com/opencaesar/oml-p2
      env:
        GITHUB_TOKEN: ${{ github.token }}
