name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Bikeshed
      run: pip install bikeshed==4.2.7

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Generate Docs with Gradle Wrapper
      run: ./gradlew ecoreToBikeshed

    - name: Bikeshed
      run: bikeshed spec io.opencaesar.oml.specification/build/bikeshed/index.bs

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.8

    - name: Build with Maven
      run: mvn verify

    - name: Publish Spec
      uses: actions/upload-pages-artifact@v3
      with:
        path: io.opencaesar.oml.specification/build/bikeshed

  deploy:

    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Spec
        id: deployment
        uses: actions/deploy-pages@v4
